import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Hero from "./Hero";
import Features from "./Features";
import Header from "./Header";
import Footer from "./Footer";
import Kontakt from "./Kontakt";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={"bg-white"}>
        <Header />
        <main>
          <Hero />
          <Features />
          <Kontakt />
        </main>
        <Footer />
      </div>





    </>
  );
};

export default Home;
